# Generated by Django 2.1.7 on 2019-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equip_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='equip_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_rights',
            new_name='rights',
        ),
        migrations.AddField(
            model_name='equipment',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
