# Generated by Django 2.1.7 on 2019-04-04 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190404_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 20, 54, 51, 471696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stopped_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 20, 54, 51, 471729, tzinfo=utc)),
        ),
    ]
