# Generated by Django 2.1.7 on 2019-04-05 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190404_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 19, 53, 47, 831235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stopped_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 19, 53, 47, 831267, tzinfo=utc)),
        ),
    ]
