# Generated by Django 2.1.7 on 2019-04-06 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190406_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 13, 57, 14, 108549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stopped_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 13, 57, 14, 108580, tzinfo=utc)),
        ),
    ]
